limud/backend/flashcards/__init__.py
from .formatting import description_as_html
from .formatting import format_any_stray_hebrew
from .state import FlashcardSide
from .state import FlashcardSorting
from .state import FlashcardRunState
from .state import make_flashcard_run

limud/routes/edit.py
from flask import current_app as app
from flask import url_for
from flask import request
from flask import redirect
from flask import render_template
from flask import session
from flask import Blueprint

from ..models import GrammaticalCategory
from ..models import Word
from ..models import create_word_from_form_dict
from ..models import update_word_from_form_dict
from ..models import database


edit = Blueprint(
    "edit", __name__,
    template_folder="templates",
    static_folder="static")


@edit.route("/edit/", methods=["GET", "POST"])
def new_word():
    if request.method == "GET":
        app.logger.debug("Editing new word")
        return render_template("edit.html", is_new=1)

    if request.method == "POST":
        app.logger.debug(f"Submitted fields: {request.form}")
        
        word = create_word_from_form_dict(**request.form)
        database.session.add(word)
        database.session.commit()
        
        app.logger.info("Added word: %s to database", word)

        # Go back to a clear edit form in case the user desires
        # to input a lot of words in a row
        return redirect(request.referrer)


@edit.route("/edit/<word_id>", methods=["GET", "POST"])
def existing_word(word_id: str):
    # Where did we come from?
    # - We could only arrive at this page from a flashcard view
    # - The ID of the word being edited is the ID of the word that was being
    #  viewed previously in the flashcard route.
    # - We don't need extra args / query strings in the route below since all
    #  the correct state should still be in flask.session.
    # Note that using the referrer URL does not work because redirect() acts
    # a bit strange.
    referrer_url = url_for("flashcards.display_run")

    if not word_id:
        app.logger.error("Invalid: edit word without a word ID! Redirecting.")

        # Do not go back to referrer_url since this should never happen!
        return redirect(url_for("home.index"))

    word = Word.query.get(word_id)
    if word is None:
        app.logger.error("Could not find word with desired ID %s", word_id)

        # Do not go back to referrer_url since this should never happen!
        return redirect(url_for("home.index"))

    app.logger.debug("Loaded word %s for edition", word)

    if request.method == "GET":
        default_values = {
            "default_value_hebrew": word.hebrew,
            "default_value_description": word.description,
            "default_value_chapter": word.chapter,
            "default_value_category": word.category.value,
            "default_value_gender": "",
            "default_value_plabs": "",
            "default_value_sgcst": "",
            "default_value_plcst": "",
        }
            
        if word.category == GrammaticalCategory.NOUN:
            default_values.update({
                "default_value_gender": word.gender,
                "default_value_plabs": word.plabs,
                "default_value_sgcst": word.sgcst,
                "default_value_plcst": word.plcst,
            })

        app.logger.debug("Editing existing word: %s", word)
        return render_template("edit.html", is_new=0, **default_values)

    if request.method == "POST":
        if "delete_button_press" in request.form:
            word_id = word.id

            database.session.delete(word)
            database.session.commit()
            app.logger.warn("Deleted word.")

            # Upon successful delete, remove the reference to the deleted word
            # from the current run...
            session["word_ids"].remove(word_id)
            num_remaining_words = len(session["word_ids"])

            if num_remaining_words:
                # If there is 1 or more word left, also update the index
                # and go back to the preceding flashcard
                session["index"] = (session["index"] - 1) % num_remaining_words
                return redirect(referrer_url)
            else:
                session.pop("index")
                return redirect(url_for("home.index"))

        app.logger.debug(f"Submitted fields: {request.form}")        
        update_word_from_form_dict(word, **request.form)
        database.session.commit()

        app.logger.info("Updated existing word: %s", word)
        return redirect(referrer_url)

limud/routes/flashcards.py
import random

from flask import current_app as app
from flask import redirect
from flask import render_template
from flask import request
from flask import session
from flask import url_for
from flask import Blueprint

from ..models import Word
from ..models import database


flashcards = Blueprint(
    "flashcards", __name__,
    template_folder="templates",
    static_folder="static")


@flashcards.route("/flashcards/", methods=["GET", "POST"])
def display_run():
    """Displays all cards in a given "run".
    
    The order and contents of the run are determined by the 'word_ids'
    variable of the state stored in flask.session.

    Thus: to display any series of words, ensure that list of IDs is
    in flask.session before accessing this route.
    """

    # Retrieve current application state:
    # - the list of words being displayed
    # - the current index relative to current list of words (or 'run')
    # - the side of the flashcard being shown (0 = front, 1 = back)
    try:
        word_ids = session["word_ids"]
    except KeyError:
        error_message = (
            "Invalid route: No 'word_ids' found in flask.session! "
            "This should never happen. Crashing."
        )
        app.logger.error(error_message)
        raise RuntimeError(error_message)

    if not word_ids:
        error_message = (
            "Invalid route: 'word_ids' in flask.session is empty! "
            "This should never happen. Crashing."
        )
        app.logger.error(error_message)
        raise RuntimeError(error_message)

    app.logger.debug("Retrieved %i words from cache.", len(word_ids))

    index = session.setdefault("index", 0)
    side = session.setdefault("side", 0)

    # Now we process any button clicks (always HTTP POST requests)
    if request.method == "POST":
        if request.form["button_press"] == "flip":
            app.logger.debug("Received request to flip")
            side = 1 - side

        if request.form["button_press"] == "previous":
            app.logger.debug("Received request for previous")
            index = (index - 1) % len(word_ids)

        if request.form["button_press"] == "next":
            app.logger.debug("Received request for next")
            index = (index + 1) % len(word_ids)

    word = Word.query.get(word_ids[index])
    app.logger.info("Retrieved word: %s from database", word)
        
    if side == 0:
        content = word.hebrew
        app.logger.debug("Showing front of flashcard")
    elif side == 1:
        content = word.description
        app.logger.debug("Showing back of flashcard ")
    else:
        raise ValueError("Invalid value for session variable 'side'!")

    # Look at these requests at the end since we need to load the word first
    if request.method == "POST":
        if request.form["button_press"] == "favorite":
            app.logger.debug("Received request to favorite")
            word.favorite = True
            database.session.commit()

        if request.form["button_press"] == "unfavorite":
            app.logger.debug("Received request to unfavorite")
            word.favorite = False
            database.session.commit()

        if request.form["button_press"] == "edit":
            app.logger.debug("Received request to edit word %s", word)
            return redirect(url_for("edit.existing_word", word_id=word.id))

    # Update state before leaving function
    session["index"] = index
    session["side"] = side

    return render_template("flashcards.html",
        content=content, side=side, favorite=int(word.favorite))


@flashcards.route("/flashcards/all")
def display_all():
    """Displays every word.
    
    Randomize by default.
    """

    words = Word.query.all()
    word_ids = [word.id for word in words]
    if not word_ids:
        app.logger.error("Query (ALL) returned no words!")
        return redirect(url_for("home.index"))
    
    if request.args.get("shuffle", False):
        random.shuffle(word_ids)

    # Set word list and reset other state
    session["word_ids"] = word_ids
    session["index"] = 0
    session["side"] = 0

    return redirect(url_for(".display_run"))


@flashcards.route("/flashcards/favorites")
def display_all_favorites():
    """Displays all favorited words.

    Randomize by default.
    """
    words = Word.query.filter_by(favorite=True).all()
    word_ids = [word.id for word in words]

    if not word_ids:
        app.logger.warn("Query (FAVORITES = TRUE) returned no words!")
        return redirect(url_for("home.index"))

    if request.args.get("shuffle", False):
        random.shuffle(word_ids)

    # Set word list and reset other state
    session["word_ids"] = word_ids
    session["index"] = 0
    session["side"] = 0

    return redirect(url_for(".display_run"))


@flashcards.route("/flashcards/chapter/<chapter_id>")
def display_by_chapter(chapter_id: str):
    """Fetches all words from a chapter, shuffles them, and displays
    them.

    Randomize by default.
    """
    chapter_id = int(chapter_id)
    words = Word.query.filter_by(chapter=chapter_id).all()
    word_ids = [word.id for word in words]

    if not word_ids:
        app.logger.warn("Query (CHAPTER = %i) returned no words!", chapter_id)
        return redirect(url_for("home.index"))

    if request.args.get("shuffle", False):
        random.shuffle(word_ids)

    # Set word list and reset other state
    session["word_ids"] = word_ids
    session["index"] = 0
    session["side"] = 0

    return redirect(url_for(".display_run"))
    

@flashcards.route("/flashcards/word/<word_id>")
def display_by_word(word_id: str):
    """Display every word but start at the word with the requisite ID.

    Do not randomize by default.
    """
    word_id = int(word_id)
    words = Word.query.all()
    word_ids = [word.id for word in words]

    if not word_ids:
        app.logger.warn("Query (ALL) returned no words!")
        return redirect(url_for("home.index"))

    try:
        index = word_ids.index(word_id)
    except ValueError:
        app.logger.error("Could not find word with desired ID %i", word_id)
        return redirect(url_for("home.index"))

    # Set word list and other state
    session["word_ids"] = word_ids
    session["index"] = index
    session["side"] = 0

    return redirect(url_for(".display_run"))

limud/routes/wotm.py
import random

from flask import current_app as app
from flask import redirect
from flask import render_template
from flask import request
from flask import session
from flask import url_for
from flask import Blueprint

from limud.backend.flashcards import FlashcardSide
from limud.backend.flashcards import FlashcardSorting
from limud.backend.flashcards import FlashcardRunState
from limud.backend.flashcards import make_flashcard_run
from limud.backend.flashcards import description_as_html
from limud.backend.models.vocabulary import GrammaticalCategory
from limud.backend.models.vocabulary import Word
from limud.backend.models.vocabulary import database
from limud.backend.wiktionary import scrape_page_from_wiktionary
from limud.backend.wiktionary import UnparsablePageError
from limud.backend.wiktionary import WiktionaryWordParse


wotm = Blueprint(
    "wotm", __name__,
    template_folder="templates",
    static_folder="static")


@wotm.route("/wotm/", methods=["GET", "POST"])
def display_wotm():
    """Displays the word most recently scraped from Wiktionary.

    Before accessing this route, proper state must be set in the Flask
    session object. See also the docs of 'FlashcardRunState'.
    """
    state = FlashcardRunState.from_flask_session()
    parse = WiktionaryWordParse(**state.words[state.index])
    word = parse.as_word()
    app.logger.debug("Current word: %s", word)

    # Process button clicks
    if request.method == "POST":
        if request.form["button_press"] == "flip":
            app.logger.debug("Received request to flip")
            state.side = ~state.side

    if state.side is FlashcardSide.FRONT:
        content = word.hebrew
        app.logger.debug("Showing front of WOTM")
    elif state.side is FlashcardSide.BACK:
        content = description_as_html(word)
        app.logger.debug("Showing back of WOTM ")
    else:
        raise ValueError("Invalid value for session variable 'side'!")

    # Save state before leaving function
    state.to_flask_session()

    return render_template("wotm.html",
        content=content,
        render_front_of_flashcard=state.side is FlashcardSide.FRONT,
        origin_url=parse.url,
    )


@wotm.route("/wotm/new")
def display_from_scrapping_random():
    """Scrapes a new word from Wiktionary and displays it.

    This works by initializing some state in the Flask session object
    via the FlashcardRunState helper object, and redirecting to the
    .display_wotm route (which assumes that state has been properly
    set up).
    """
    parses = scrape_page_from_wiktionary(retry=True)
    app.logger.debug("Parsed words: %s", *(p.word for p in parses))

    FlashcardRunState(
        words=parses,
        index=0,
        side=FlashcardSide.FRONT,
        progress=[0, len(parses)],
    ).to_flask_session()

    return redirect(url_for(".display_wotm"))


@wotm.route("/wotm/<word>")
def display_from_scrapping_word(word: str):
    """Scrapes a new word from Wiktionary and displays it.

    This works by initializing some state in the Flask session object
    via the FlashcardRunState helper object, and redirecting to the
    .display_wotm route (which assumes that state has been properly
    set up).
    """
    url = f"https://en.wiktionary.org/w/index.php?title={word}"
    parses = scrape_page_from_wiktionary(url=url)
    app.logger.debug("Parsed words: %s", *(p.word for p in parses))

    FlashcardRunState(
        words=parses,
        index=0,
        side=FlashcardSide.FRONT,
        progress=[0, len(parses)],
    ).to_flask_session()

    return redirect(url_for(".display_wotm"))

limud/templates/edit.html
{% extends "layout.html" %}
{% block body %}
<form method="post">
<div class="edit-form centered">
    <label for="hebrew">Hebrew</label>
    <input type="text" id="hebrew" name="hebrew" dir="rtl" xml:lang="he" lang="he"
        value="{{ default_value_hebrew }}"></input>
    
    <label for="description">Translation</label>
    <input type="text" id="description" name="description"
        value="{{ default_value_description }}"></input>

    <label for="category">Grammatical class</label>
    <select name="category" id="category">
      <option value="noun" 
          {% if default_value_category == "noun" %} selected {% endif %}>
          Noun
      </option>
      <option value="verb" 
          {% if default_value_category == "verb" %} selected {% endif %}>
          Verb
      </option>
      <option value="adjective" 
          {% if default_value_category == "adjective" %} selected {% endif 
            %}>
          Adjective
      </option>
      <option value="adverb" 
          {% if default_value_category == "adverb" %} selected {% endif %}>
          Adverb
      </option>
    </select> 
    
    <label for="chapter">Chapter (or group)</label>
    <input type="number" id="chapter" name="chapter" min="1"
        value="{{ default_value_chapter }}"></input>

    <label for="gender">Gender (optional)</label>
    <select name="gender" id="gender">
        <option value="" 
            {% if default_value_gender == "" %} selected {% endif %}>
            N/A
        </option>
        <option value="masculine" 
            {% if default_value_gender == "masculine" %} selected {% endif %}>
            Masculine
        </option>
        <option value="feminine" 
            {% if default_value_gender == "feminine" %} selected {% endif %}>
            Feminine
        </option>
    </select>

    <label for="plabs">Plural absolute (optional)</label>
    <input type="text" id="plabs" name="plabs" dir="rtl" xml:lang="he" lang="he"
        value="{{ default_value_plabs }}"></input>

    <label for="sgcst">Singular construct (optional)</label>
    <input type="text" id="sgcst" name="sgcst" dir="rtl" xml:lang="he" lang="he"
        value="{{ default_value_sgcst }}"></input>

    <label for="plcst">Plural construct (optional)</label>
    <input type="text" id="plcst" name="plcst" dir="rtl" xml:lang="he" lang="he"
        value="{{ default_value_plcst }}"></input>
    
    {% if is_new == 1 %}
        <br/>
        <button class="flashcard-button">
            Add new word to vocabulary
        </button>
    {% else %}
        <br/>
        <!-- This should not send any value since we assume the form's keys
             are all table column names. -->
        <button class="flashcard-button">
            Update existing word
        </button>
        
        <br/>
        <!-- Below we need a name fields to distinguish the two button presses -->
        <button class="flashcard-button" name="delete_button_press" onclick="confirmDelete()">
            Delete word from vocabulary
            <script>
            function confirmDelete() {
              confirm("Are you sure you want to delete this word? THIS OPERATION CANNOT BE UNDONE.");
            }
            </script>          
        </button>
    {% endif %}
</div>
</form>
{% endblock %}

limud/templates/flashcard.html
{% extends "layout.html" %}
{% block body %}
<div class="centered">
<table style="border-collapse: collapse; width: 100%;" border="1">
    <tbody>
    <tr>
    <td style="width: 90%; text-align: center;">
    {% if obverse %}
    <span xml:lang="he" lang="he" class="flashcard-word">{{ display_text }}</span>
    {% else %}
    <span xml:lang="he" lang="he">{{ display_text }}</span>
    {% endif %}
    </td>
    </tr>
    </tbody>
</table>
<table style="border-collapse: collapse; width: 100%;" border="1">
    <tbody>
    <tr>
    <td style="text-align: center;">
        <button class="flashcard-button">&#9664;</button>
    </td>
    <td style="text-align: center;">
        <button class="flashcard-button">Randomize</button>
    </td>
    <td style="text-align: center;">
        <button class="flashcard-button">Flip</button>
    </td>
    <td style="text-align: center;">
        <button class="flashcard-button">Edit</button>
    </td>
    <td style="text-align: center;">
        <button class="flashcard-button">Delete</button>
    </td>
    <td style="text-align: center;">
        <div id="ck-button">
            <label>
            <input type="checkbox" id="favorite" name="favorite">
            <span>Favorite</span>
            </label>
         </div>
    </td>
    <td style="text-align: center;">
        <button class="flashcard-button">&#9654;</button>
    </td>
    </tr>
    </tbody>
</table>
</div>
{% endblock %}

limud/templates/flashcards.html
{% extends "layout.html" %}
{% block body %}
<div class="centered">
<table style="border-collapse: collapse; width: 100%;" border="1">
    <tbody>
    <tr>
    <td style="width: 90%; text-align: center;">
        {% if side == 0 %}
        <span xml:lang="he" lang="he" class="flashcard-word">{{ content }}</span>
        {% else %}
        <span xml:lang="he" lang="he">{{ content }}</span>
        {% endif %}
    </td>
    </tr>
    </tbody>
</table>
<table style="border-collapse: collapse; width: 100%;" border="1">
    <tbody>
    <tr>
    <td style="text-align: center;">
        <form method="POST">
        <button class="flashcard-button"
            type="submit" name="button_press" value="previous">&#9664;</button>
        </form>
    </td>
    <td style="text-align: center;">
        <form method="POST">
            <button class="flashcard-button"
                type="submit" name="button_press" value="edit">Edit</button>
        </form>
    </td>
    <td style="text-align: center;">
        <form method="POST">
        <button class="flashcard-button"
            type="submit" name="button_press" value="flip">Flip</button>
        </form>
    </td>
    <td style="text-align: center;">
        <form method="POST">
         {% if favorite == 1 %}
         <button class="flashcard-button"
            type="submit" name="button_press" value="unfavorite">Unfavorite</button>
        {% else %}
        <button class="flashcard-button"
            type="submit" name="button_press" value="favorite">Favorite</button>
        {% endif %}
        </form>
    </td>
    <td style="text-align: center;">
        <form method="POST">
            <button class="flashcard-button"
                type="submit" name="button_press" value="next">&#9654;</button>
        </form>
    </td>
    </tr>
    </tbody>
</table>
</div>
{% endblock %}

limud/templates/index.html
{% extends "layout.html" %}
{% block body %}
<body>
    <!-- Show a welcome message -->
    <span xml:lang="he" lang="he" class="splash-screen-word centered">שָׁלוֺם</span>
</body>
{% endblock %}

limud/templates/layout.html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}" />
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" />
    <title>Biblical Hebrew flashcards</title>
    
    <!-- Display dropdown contextual menu -->
    <div class="dropdown">
        <button class="dropbtn-main" id="main-menu">Menu</button>
        <div class="dropdown-content">
            <a href="{{ url_for('home.index') }}">Home</a>
            <a href="{{ url_for('edit.new_word') }}">Add flashcard</a>
            <div class="dropdown">
                <button class="dropbtn">Review flashcards</button>
                <div class="dropdown-content">
                    <a href="{{ url_for('flashcards.display_all') }}">
                        &nbsp;&nbsp;&nbsp;&nbsp;Everything
                    </a>
                    <a href="{{ url_for('flashcards.display_all_favorites') }}">
                        &nbsp;&nbsp;&nbsp;&nbsp;All favorites
                    </a>
                    <div class="dropdown">
                        <button class="dropbtn">
                            &nbsp;&nbsp;&nbsp;&nbsp;By chapter
                        </button>
                        <div class="dropdown-content">
                        {% for cid in all_chapters_ids %}
                            <a href="{{ url_for('flashcards.display_by_chapter', chapter_id=cid) }}">
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Chapter {{ cid }}
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> 
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>  

limud/templates/practice.html
{% extends "layout.html" %}
{% block body %}
<div class="centered-container flashcard-container">
<table class="flashcard-container-progress-bar">
    <!-- Progress bar is just a div tag -->
    <tbody><tr><td>
    <div style="width: {{ progress_percent }}%;" />
    </td></tr></tbody>
</table>
<table class="flashcard-container-word">
    <tbody>
    <tr>
    <td>
        <form method="POST">
            <button type="submit" name="button_press" value="flip">
                <span class="{{ 'flashcard-front' if render_hebrew_large else 'flashcard-back' }}">
                    <!-- Safe is because we might format Hebrew text in the backend -->
                    <!-- TODO: Obviously this is horrible, security-wise... -->
                    {{ content | safe }}
                </span>
            </button>
        </form>
    </td>
    </tr>
    </tbody>
</table>
<table class="flashcard-container-buttons">
    <tbody>
    <tr>
    {% if render_reveal_button  %}
        <td style="text-align: center;">
            <form method="POST">
            <button class="flashcard-button"
                type="submit" name="button_press" value="flip">Reveal</button>
            </form>
        </td>
    {% else %}
        <td style="text-align: center;">
            <form method="POST">
            <button class="flashcard-button"
                type="submit" name="button_press" value="incorrect">&#10060;</button>
            </form>
        </td>
        {% if render_favorite_button %}
        <td style="text-align: center;">
            <form method="POST">
            {% if favorite == 1 %}
            <button class="flashcard-button"
                type="submit" name="button_press" value="unfavorite">Unfavorite</button>
            {% else %}
            <button class="flashcard-button"
                type="submit" name="button_press" value="favorite">Favorite</button>
            {% endif %}
            </form>
        </td>
        {% endif %}
        <td style="text-align: center;">
            <form method="POST">
                <button class="flashcard-button"
                type="submit" name="button_press" value="correct">&#9989;</button>
            </form>
        </td>
    {% endif %}
    </tr>
    </tbody>
</table>
</div>
{% endblock %}

limud/templates/review.html
{% extends "layout.html" %}
{% block body %}
<div class="centered-container flashcard-container">
<table class="flashcard-container-progress-bar">
    <!-- Progress bar is just a div tag -->
    <tbody><tr><td>
    <div style="width: {{ progress_percent }}%;" />
    </td></tr></tbody>
</table>
<table class="flashcard-container-word">
    <tbody>
    <tr>
    <td>
        <form method="POST">
            <button type="submit" name="button_press" value="flip">
                {% if render_front_of_flashcard  %}
                <span class="flashcard-front">{{ content }}</span>
                {% else %}
                <span class="flashcard-back">{{ content }}</span>
                {% endif %}
            </button>
        </form>
    </td>
    </tr>
    </tbody>
</table>
<table class="flashcard-container-buttons">
    <tbody>
    <tr>
    <td style="text-align: center;">
        <form method="POST">
        <button class="flashcard-button"
            type="submit" name="button_press" value="previous">&#9664;</button>
        </form>
    </td>
    <td style="text-align: center;">
        <form method="POST">
            <button class="flashcard-button"
                type="submit" name="button_press" value="edit">Edit</button>
        </form>
    </td>
    <td style="text-align: center;">
        <form method="POST">
        <button class="flashcard-button"
            type="submit" name="button_press" value="flip">Flip</button>
        </form>
    </td>
    <td style="text-align: center;">
        <form method="POST">
        {% if favorite %}
         <button class="flashcard-button"
            type="submit" name="button_press" value="unfavorite">Unfavorite</button>
        {% else %}
        <button class="flashcard-button"
            type="submit" name="button_press" value="favorite">Favorite</button>
        {% endif %}
        </form>
    </td>
    <td style="text-align: center;">
        <form method="POST">
            <button class="flashcard-button"
                type="submit" name="button_press" value="next">&#9654;</button>
        </form>
    </td>
    </tr>
    </tbody>
</table>
</div>
{% endblock %}

limud/templates/wotm.html
{% extends "layout.html" %}
{% block body %}
<div class="centered-container flashcard-container">
<table class="flashcard-container-progress-bar">
    <!-- Empty table to force the "flashcard" to be the same size
         as in flashcards.html or in game.html. -->
    <tbody><tr><td>
    <div style="width: 0%;" />
    </td></tr></tbody>
</table>
<table class="flashcard-container-word">
    <tbody>
    <tr>
    <td>
        <form method="POST">
            <button type="submit" name="button_press" value="flip">
                {% if render_front_of_flashcard  %}
                <span class="flashcard-front">{{ content }}</span>
                {% else %}
                <span class="flashcard-back">{{ content }}</span>
                {% endif %}
            </button>
        </form>
    </td>
    </tr>
    </tbody>
</table>
<table class="flashcard-container-buttons">
    <tbody>
    <tr>
    <td style="text-align: center;">
        <a href="{{ url_for('wotm.display_from_scrapping_random') }}">
            <button class="flashcard-button">New Word</button></a>
    </td>
    <td style="text-align: center;">
        <form method="POST">
        <button class="flashcard-button"
            type="submit" name="button_press" value="flip">Flip</button>
        </form>
    </td>
    <td style="text-align: center;">
        <a href="{{ origin_url }}">
            <button class="flashcard-button">Source</button></a>
    </td>
    </tr>
    </tbody>
</table>
</div>
{% endblock %}